baseURL = "https://louiskwt.github.io/blog/"
languageCode = "en-us"
title = "Hacking to the Gate"
theme="archie"
copyright = "© louiskwt"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags


# Main menu Items

